import Head from "next/head";
import { Box, Heading } from "@/components/ui";
import { ja } from "@/shared/lang/ja";
import Link from "next/link";
import homeScreenStyle from "./home.css";

function HomeScreen() {
    return (
        <>
            <Head>
                <title>Pages router template v15.3</title>
                <meta name="description" content="Generated by pages" />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Box as="main" className={homeScreenStyle.pageRoot}>
                <Box as="section" className={homeScreenStyle.container}>
                    <Heading className={homeScreenStyle.heading}>
                        {ja.app.home.title}
                    </Heading>

                    <ul className={homeScreenStyle.navList}>
                        <li>
                            <Link
                                className={homeScreenStyle.navItemLink}
                                href="/server-side-render"
                            >
                                {ja.app.home.toServerSideRender}
                            </Link>
                        </li>
                        <li>
                            <Link
                                className={homeScreenStyle.navItemLink}
                                href="/static-generator"
                            >
                                {ja.app.home.toStaticPotter}
                            </Link>
                        </li>
                        <li>
                            <Link
                                className={homeScreenStyle.navItemLink}
                                href="/dynamic-render"
                            >
                                {ja.app.home.toSingleDynamicPotter}
                            </Link>
                        </li>
                    </ul>
                </Box>
            </Box>
        </>
    );
}

export default HomeScreen;
