import Head from "next/head";
import { Box, Heading } from "@/components/ui";
import { ja } from "@/shared/lang/ja";
import Link from "next/link";

function HomeScreen() {
    return (
        <>
            <Head>
                <title>Pages router template v15.3</title>
                <meta name="description" content="Generated by pages" />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Box as="main">
                <Heading>{ja.app.home.title}</Heading>

                <Box>
                    <Link href="/server-side-render">
                        {ja.app.home.toServerSideRender}
                    </Link>

                    <br />
                    <Link href="/static-generator">
                        {ja.app.home.toStaticPotter}
                    </Link>

                    <br />

                    <Link href="/dynamic-render">
                        {ja.app.home.toSingleDynamicPotter}
                    </Link>
                </Box>
            </Box>
        </>
    );
}

export default HomeScreen;
